print("============================================")
print("Python 3 Programming Specialization")
print("Course 1 : Python Basics")
print("Week 1 : Introduction to the Specialization")
print("============================================")
print("======== 1.2. Values and Data Types ========")
print("--------------------------------------------")
print(100)
print(3.14)
print("Hello world")
print("")
print(3.2)
print("Hello World!")
print("============================================")
print("======= 1.3. Operators and Operands ========")
print("--------------------------------------------")
print(100 + 200)
print(5 - 2)
print(2 * 4)
print(10 / 3)
print(10 // 3)
print(10 % 3)
print(4 ** 2)
print(10 + 20 / 2)
print((10 + 20) / 2)
print("")
print(20 + 32)
print(5 ** 2)
print((5 + 9) * (15 - 7))
print(9 / 5)
print(5 / 9)
print(9 // 5)
print(7.0 / 3.0)
print(7.0 // 3.0)
print(7 // 3)
print(7 % 3)
print(18 / 4)
print(18.0 // 4)
print(18 % 4)
print("")
print(2 * (3-1))
print((1+1)**(5-2))
print(2**1+1)
print(3*1**3)
print(2*3-1)
print(5-2*2)
print(6-3+2)
print(6-(3+2))
print("")
print(2 ** 3 ** 2)
print((2 ** 3) ** 2)
print(16 - 2 * 5 // 3 + 1)
print("============================================")
print("============ 1.4.Function Calls=============")
print("--------------------------------------------")
def square(num):
    return num * num

def sub(num1, num2):
    return num1 - num2

print(square(3))
square(4)
print(sub(6,4))
print(sub(5,9))
print("")
print(square(3) + 2)
print(sub(square(3), square(1 + 1)))
print("")
print(square)
print(square(3))
print("============================================")
